Zidras/DBM-Warmane

DBM-Icecrown/TheCrimsonHall/BPCouncil.lua
There is an inherent random factor associated with these timers. The only timer that is reproducible is Empowered Shock Vortex to Empowered Shock Vortex, or Empowered Shock Vortex to the Shock Vortex right after it (30 seconds). Everything else fluctuates, based on logs.
To mitigate the random factor, I have passing the Keep argument as true, so the bar stays on screen until cancelled of restarted.
Additionally, I am checking bar remaining timers and started status, which might not be needed at all with the Keep now enabled.
=> BPC: add Empowered Shock Vortex timer (Fix #69)

DBM-GUI/DBM-GUI_DropDown.lua, DBM-Gruul/Gruul.lua, DBM-Gruul/localization.en.lua, DBM-Gruul/localization.kr.lua, DBM-Gruul/localization.ru.lua, DBM-Naxx/ConstructQuarter/Thaddius.lua, DBM-Naxx/localization.en.lua
There is a bug with the dropdown in Thaddius options. If the string width was too high the button just went out of clickable bounds. 
Note that it was possible to fix this by adding \n to the string with high width in locale instead, but it made the dropdown look not so nice. If you think this will break something with menus then I will PR the \n fix instead. From what I checked everything seemed to stay same though.
Before:
After:
I also fixed the dropdown button overlapping in Gruul options.
Updated one looks like this
=> Fix Thaddius polarity shift dropdown and text and Gruul dropdown position

DBM-ChamberOfAspects/Obsidian/Sartharion.lua, DBM-Naxx/ArachnidQuarter/Faerlina.lua, DBM-Naxx/ArachnidQuarter/Maexxna.lua, DBM-Naxx/ConstructQuarter/Grobbulus.lua, DBM-Naxx/MilitaryQuarter/Horsemen.lua
Timers are based on when this was current content on Frostmourne S2. Assuming that they are still same as of now.
Note that for Grobbulus I added approximate timer for Slime Spray based on what I researched. It seems that each pull timers are different/randomized:
**25-man pull from May 2021:
34 after pull - 30 - 56 - 28 - 60**
**25-man pull from June 2021:
30 after pull - 32 - 62 - 24 - 62**
**25-man pull from July 2021:
30 after pull - 34 - 60 - 34 - 58 - 32**
**25-man pull from August 2021:
34 after pull - 32 - 56 - 32 - 56**
**25-man pull from Lordaeron in October 2021:
32 after pull - 26 - nothing for 57**
**10-man pull from Icecrown in April 2021:
36 after pull - 30**
I don't think they changed timers so often, it seems like each pull it just randomizes intervals to be used during …
=> T7 add a couple timers

DBM-ChamberOfAspects/Obsidian/Sartharion.lua
Looks like old code wanted to use Blizzard API to check for debuff but used DBM function instead, this resulted in nil being returned and timers not activating for Drake mechanics on OS 1D+.
https://github.com/Zidras/DBM-Warmane/blob/88728ccd0e7b8d1a3724fe9acadb5234918d1134/DBM-Core/DBM-Core.lua#L5871-L5880
=> Sartharion: fix Drake debuff check

DBM-Naxx/FrostwyrmLair/Kel'Thuzad.lua
12 yards seems to be the safer/more consistent option. Since the explosion range itself is 10 yards, sometimes it shows that nobody is in range and people still get touched by the damage.
=> Kel'Thuzad: safer Detonate Mana range

DBM-Naxx/MilitaryQuarter/Horsemen.lua
Thane and Baron marks are cast at the same time, also Lady and Zeliek marks are cast at the same time of each other and earlier than 5 seconds after Thane/Baron mark, so the antispam is blocking other mark timers from starting.
Transcriptor log:
[Naxx_FourHorsemen_transcript.txt](https://github.com/Zidras/DBM-Warmane/files/8682659/Naxx_FourHorsemen_transcript.txt)
=> Four Horsemen: fix AntiSpam blocking mark timers

DBM-ChamberOfAspects/Obsidian/Sartharion.lua
Canceling the timer on first whelp targeted. Right now the keep argument makes the timer last for the whole fight.
=> Sartharion: cancel whelps timer after whelps spawn

DBM-Core/DBM-RangeCheck.lua
If DBM.Options.DontRestoreRange is true then restoreRange will be nil, since it doesn't get assigned non-nil anywhere else. 
Otherwise it will be set to the current range passed by SetBossRange(), since it passes forceshow argument as true.
https://github.com/Zidras/DBM-Warmane/blob/f989be67418f4053c24b3d9397fe0b9eac4de721/DBM-Core/DBM-RangeCheck.lua#L1249-L1260
Then DisableBossMode() will set current range either to nil (and lua nil error from OnUpdate function) or the one that bossMode was using rather than previous one before it.
https://github.com/Zidras/DBM-Warmane/blob/f989be67418f4053c24b3d9397fe0b9eac4de721/DBM-Core/DBM-RangeCheck.lua#L1262-L1271
=> Range Check: attempt to fix incorrect previous range after bossMode

DBM-Serpentshrine/DBM-Serpentshrine.toc, DBM-Serpentshrine/Tidewalker.lua, DBM-Serpentshrine/localization.cn.lua, DBM-Serpentshrine/localization.de.lua, DBM-Serpentshrine/localization.en.lua, DBM-Serpentshrine/localization.es.lua, DBM-Serpentshrine/localization.fr.lua, DBM-Serpentshrine/localization.kr.lua, DBM-Serpentshrine/localization.ru.lua, DBM-Serpentshrine/localization.tw.lua
1. Tidewalker casts Watery Grave every 30s.
2. Watery Grave can miss, so changed >=4 to >=1.
3. [Warmane bug?] Watery Grave doesn't always cast every 30s, even though the boss emote still goes off on schedule. Use the boss emote instead of the aura_applied to trigger the timer. (Skips to every other -> 60s, bugged on one pull.)
4. [Warmane bug?] Tidewalker doesn't cast Earthquake after his first one, but the boss emote still goes off on schedule. Use the boss emote instead of the cast to trigger the timer. (Seems like if he is tanked in one spot, he won't cast Earthquake again. He will cast it correctly each time he is re-positioned after casting Earthquake.)
5. Added the boss emotes to en localization.
=> SSC-Tidewalker1

DBM-BlackTemple/Najentus.lua, DBM-BlackTemple/Supremus.lua
Naj'entus 
5 min (300s) enrage timer
Supremus
* 9min and 10 second enrage (starts and ramps up during the kite phase, but doesn't kill you yet), you basically have until 10 minutes to kill him*
I feel having the enrage timer at 10 min (600s) gives the best representation of the fight.
=> Update for Naj'entus and Supremus Enrage timers

DBM-BlackTemple/TeronGorefiend.lua
I've noticed that warmane has added a 5 minute enrage timer to the teron Gorefiend fight in Black temple timewalking.
This excerpt from the transcript should show that the boss has a 300second enrage timer:
-------------------------------
["UNIT_SPELLCAST_SUCCEEDED"] = {
"Berserk-npc:22871-332 = pull:299.3", -- [1]
-------------------------------
["MONSTER"] = {
"<13.19 22:32:06> [CHAT_MSG_MONSTER_YELL] Vengeance is mine!:Teron Gorefiend:::::0:0::0:3525::0:", -- [1]
["UNIT_SPELLCAST"] = {
"<313.20 22:37:06> [UNIT_SPELLCAST_SUCCEEDED] Teron Gorefiend(*player name redacted*) -Berserk- [[target:Berserk::0:]]", -- [74]
--------------------
If the first was not enough, here you can see that the difference between the combat start and berserk is also 300 seconds
=> Add enrage timer to TeronGorefiend.lua

DBM-Core/DBM-Core.lua, DBM-Core/modules/Icons.lua
SetIconByTable and SetIconBySortedTable was bumping icon index before firing the returnFunc, causing all icon announces to be shifted by one index.
Verified by Emi on Sindragosa: Frost Beacon icon announces were being index-shifted by +1 and ended up on {rt9}
=> Core: fix icon announcing

DBM-Icecrown/TheFrozenThrone/LichKing.lua
Ensures proper functioning, even with a broken combat log. Not only works around a long lasting issue with users experiencing a full CLEU blackout, but also a newer bug with Warmane servers not properly handling these packets and client combat log misbehaves.
=> ICC-LK: switch CLEU cast start to UNIT

DBM-ChamberOfAspects/Ruby/Saviana.lua
Flame Beacon applies disorient to targets, so they wander and spread damage to nearby players as well
=> RS-Saviana: increase Flame Beacon spread range to 12yd

DBM-Coliseum/localization.cn.lua
Fix zhCN boss chat message. The original one mixed up Emerge and Burrow yell msg. This leads to incorrect Shadow Strike timer.
=> Fix zhCN Annub chat message

DBM-TheEye/DBM-TheEye.toc
TK .toc file has the same Map ID as Hyjal, causing both DBMS to load in Hyjal:
https://github.com/Zidras/DBM-Warmane/blob/main/DBM-Hyjal/DBM-Hyjal.toc#L24
=> TK: Correct map ID

DBM-Core/DBM-Core.lua
Fix filtering by unit in UNIT_* events.
Fixes event filters such as "UNIT_HEALTH boss1" not working at all.
=> Core: Fix filtering UNIT_* events by unitId

DBM-Core/DBM-Core.lua
When RL use /dbm broadcast timer, all raiders' DBM shows the timer, but this timer can't be picked up by WeakAuras. Added an event so this should work.
=> fix PizzaTimer event can't be picked up by weakauras

DBM-Core/DBM-RangeCheck.lua
The [[MPQ Patch] Classic/BC Dungeon Maps for WotLK](https://forum.warmane.com/showthread.php?t=424250) map patch returns ManaTombs as the mapFileName from GetMapInfo() function. I don't know if there are other patches that make it as Mana-Tombs, so I just added an additional entry with the alternative name. Otherwise this throws an error:
https://github.com/Zidras/DBM-Warmane/blob/60a9631f452a9a4e41d84b5104e14239940b3163/DBM-Core/DBM-Core.lua#L6556-L6563
Here is what GetMapInfo() prints when standing inside Mana-Tombs with this specific patch:
=> Add Mana Tombs alternative Map File Name

DBM-Magtheridon/Magtheridon.lua
Just missing a small check for the alternate yell msg.
=> Magtheridon: Fix Phase 2 setting on any boss yell

DBM-Magtheridon/Magtheridon.lua
Forgot to include the counter when adding time on P3 transition.
On a side note, apparently some people are having overlapping bars after the latest update? From what I heard Conflag bar and Blast Nova was overlapping, but I didn't have this issue. Maybe you have some more insight into it?
=> Magtheridon: Add blast nova counter to addtime

DBM-Magtheridon/Magtheridon.lua
There are scenarios where Conflagration and Quake can get "queued" by a few seconds. Conflag has the keep arg already, so just adding it to Quake also. Also figured might as well add warnings for those 2 spells.
Also edited the counter to be in line with standard as seen in other bosses where it starts from 0.
=> Magtheridon: Add Warnings and keep arg to Quake, small edits

DBM-PvP/PvPGeneral.lua
max resources in AB on onyxia realm are 2000
possibly different on other realms?
suggested solution under testing to parse it correctly. needs cross realm testing
all on english locale
**Onyxia** (level 60+) **AB:**
**Blackrock** (level 80) **AB:**
**Blackrock** (level 80) **EOS:**
=> [PVP] AB/EOS parse maxResources from GetWorldStateUIInfo score text

DBM-Party-BC/Auct_ShadowLabyrinth/Murmur.lua
Per Transcriptor Log adding missing spell id of a Murmur's Touch debuff in HC version of a fight.
[Transcriptor.txt](https://github.com/user-attachments/files/18030927/Transcriptor.txt)
=> SL HC: Murmur - Murmur's Touch

DBM-Karazhan/MaidenOfVirtue.lua, DBM-Karazhan/Netherspite.lua
Maiden of Virtue: Add keep arg to Repentance CD
Netherspite: Fix icon texture
=> Karazhan: Update timers

DBM-BlackTemple/Shahraz.lua
Popular WA's used to coordinate spread during fatal attraction rely on DBM marking star, circle and diamond. DBM mod for Mother defines them as used icons, but only ever marks star
=> BT-Shahraz: Use more than 1 mark of fatal attraction

DBM-Core/DBM-Core.lua
adds simpType to the Timer metatable seen here:
https://github.com/Zidras/DBM-Warmane/blob/9b4f7af2860ade08c3c66e05fff9dc4c43d674aa/DBM-Core/DBM-Core.lua#L10783
Lines were cherry picked, but followed though. There was no way for me to git blame it, because it got merged from unified and even on unified those line came from somewhere...
=> [WeakAuras Parity] Add pull, break simpType to timer metatable

DBM-Naxx/MilitaryQuarter/Razuvious.lua
The spell has no icon, so it's using the default engineering icon.
Added the https://www.wowhead.com/wotlk/icon=132351/ability-warrior-rallyingcry icon instead. I looked at some of the warrior icons and this seemed like the best fit. There is also this spell https://www.wowhead.com/wotlk/spell=42708/staggering-roar, which uses the same icon.
=> Instructor Razuvious: Add icon to Disrupting Shout
